// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: uCNC-GFX

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_startup
void ui_startup_screen_init(void);
lv_obj_t * ui_startup;
lv_obj_t * ui_startup_label_versioninfo;
lv_obj_t * ui_startup_image_image1;


// SCREEN: ui_idle
void ui_idle_screen_init(void);
lv_obj_t * ui_idle;
lv_obj_t * ui_idle_container_header2;
void ui_event_idle_button_btnunlock(lv_event_t * e);
lv_obj_t * ui_idle_button_btnunlock;
lv_obj_t * ui_idle_image_image8;
lv_obj_t * ui_idle_image_image17;
lv_obj_t * ui_idle_container_statusinfo;
lv_obj_t * ui_idle_label_statuslabel;
lv_obj_t * ui_idle_label_statusvalue;
void ui_event_idle_button_btnholdres(lv_event_t * e);
lv_obj_t * ui_idle_button_btnholdres;
lv_obj_t * ui_idle_image_image7;
lv_obj_t * ui_idle_image_image12;
lv_obj_t * ui_idle_container_body2;
lv_obj_t * ui_idle_container_container7;
void ui_event_idle_button_btnhome(lv_event_t * e);
lv_obj_t * ui_idle_button_btnhome;
lv_obj_t * ui_idle_image_image9;
void ui_event_idle_button_btnjog(lv_event_t * e);
lv_obj_t * ui_idle_button_btnjog;
lv_obj_t * ui_idle_image_image10;
void ui_event_idle_button_btnsettings(lv_event_t * e);
lv_obj_t * ui_idle_button_btnsettings;
lv_obj_t * ui_idle_image_image11;
lv_obj_t * ui_idle_container_container1;
lv_obj_t * ui_idle_container_modalmodesinfo;
lv_obj_t * ui_idle_label_modalmodeslabel;
lv_obj_t * ui_idle_label_modalmodesvalue;
lv_obj_t * ui_idle_container_container3;
lv_obj_t * ui_idle_label_unitsvalue;
lv_obj_t * ui_idle_container_feedinfo;
lv_obj_t * ui_idle_label_feedlabel;
lv_obj_t * ui_idle_label_feedvalue;
lv_obj_t * ui_idle_container_toolnumberinfo;
lv_obj_t * ui_idle_label_toolnumberlabel;
lv_obj_t * ui_idle_label_toolnumbervalue;
lv_obj_t * ui_idle_container_toolspeedinfo;
lv_obj_t * ui_idle_label_toolspeedlabel;
lv_obj_t * ui_idle_label_toolspeedvalue;
lv_obj_t * ui_idle_container_switchinfo;
lv_obj_t * ui_idle_label_switchlabel;
lv_obj_t * ui_idle_label_switchvalue;
lv_obj_t * ui_idle_container_container8;
lv_obj_t * ui_idle_axisinfo_axisinfox;
lv_obj_t * ui_idle_axisinfo_axisinfoy;
lv_obj_t * ui_idle_axisinfo_axisinfoz;
lv_obj_t * ui_idle_container_container9;
lv_obj_t * ui_idle_axisinfo_axisinfoa;
lv_obj_t * ui_idle_axisinfo_axisinfob;
lv_obj_t * ui_idle_axisinfo_axisinfoc;
lv_obj_t * ui_idle_container_footer2;
void ui_event_idle_button_btnprev2(lv_event_t * e);
lv_obj_t * ui_idle_button_btnprev2;
lv_obj_t * ui_idle_label_btnprevlabel2;
void ui_event_idle_button_btnnext2(lv_event_t * e);
lv_obj_t * ui_idle_button_btnnext2;
lv_obj_t * ui_idle_label_btnnextlabel2;
void ui_event_idle_button_btnenter2(lv_event_t * e);
lv_obj_t * ui_idle_button_btnenter2;
lv_obj_t * ui_idle_label_btnenterlabel2;


// SCREEN: ui_navigate
void ui_navigate_screen_init(void);
lv_obj_t * ui_navigate;
lv_obj_t * ui_navigate_panel_header;
lv_obj_t * ui_navigate_label_headerlabel;
void ui_event_navigate_button_btnclose(lv_event_t * e);
lv_obj_t * ui_navigate_button_btnclose;
lv_obj_t * ui_navigate_image_image16;
lv_obj_t * ui_navigate_container_body;
lv_obj_t * ui_navigate_container_menuitem0;
lv_obj_t * ui_navigate_label_menuitemlabel0;
lv_obj_t * ui_navigate_label_menuitemvalue0;
lv_obj_t * ui_navigate_container_menuitem1;
lv_obj_t * ui_navigate_label_menuitemlabel1;
lv_obj_t * ui_navigate_label_menuitemvalue1;
lv_obj_t * ui_navigate_container_menuitem2;
lv_obj_t * ui_navigate_label_menuitemlabel2;
lv_obj_t * ui_navigate_label_menuitemvalue2;
lv_obj_t * ui_navigate_container_menuitem3;
lv_obj_t * ui_navigate_label_menuitemlabel3;
lv_obj_t * ui_navigate_label_menuitemvalue3;
lv_obj_t * ui_navigate_container_menuitem4;
lv_obj_t * ui_navigate_label_menuitemlabel4;
lv_obj_t * ui_navigate_label_menuitemvalue4;
lv_obj_t * ui_navigate_container_menuitem5;
lv_obj_t * ui_navigate_label_menuitemlabel5;
lv_obj_t * ui_navigate_label_menuitemvalue5;
lv_obj_t * ui_navigate_panel_footernav;
void ui_event_navigate_button_btnprev(lv_event_t * e);
lv_obj_t * ui_navigate_button_btnprev;
lv_obj_t * ui_navigate_image_image13;
void ui_event_navigate_button_btnnext(lv_event_t * e);
lv_obj_t * ui_navigate_button_btnnext;
lv_obj_t * ui_navigate_image_image14;
void ui_event_navigate_button_btnenter(lv_event_t * e);
lv_obj_t * ui_navigate_button_btnenter;
lv_obj_t * ui_navigate_image_image15;


// SCREEN: ui_edit
void ui_edit_screen_init(void);
lv_obj_t * ui_edit;
lv_obj_t * ui_edit_panel_header;
lv_obj_t * ui_edit_label_headerlabel;
void ui_event_edit_button_btnclose(lv_event_t * e);
lv_obj_t * ui_edit_button_btnclose;
lv_obj_t * ui_edit_image_image2;
lv_obj_t * ui_edit_container_bodyedit;
lv_obj_t * ui_edit_textarea_vareditinput;
lv_obj_t * ui_edit_container_footeredit;
void ui_event_edit_keyboard_keyboardedit(lv_event_t * e);
lv_obj_t * ui_edit_keyboard_keyboardedit;


// SCREEN: ui_jog
void ui_jog_screen_init(void);
lv_obj_t * ui_jog;
lv_obj_t * ui_jog_panel_header;
lv_obj_t * ui_jog_label_headerlabel;
void ui_event_jog_button_btnclose(lv_event_t * e);
lv_obj_t * ui_jog_button_btnclose;
lv_obj_t * ui_jog_image_image6;
lv_obj_t * ui_jog_container_body1;
lv_obj_t * ui_jog_container_jogaxisinfo;
lv_obj_t * ui_jog_label_jogaxislabel;
lv_obj_t * ui_jog_label_jogaxisvalue;
lv_obj_t * ui_jog_panel_panel1;
lv_obj_t * ui_jog_container_container2;
lv_obj_t * ui_jog_label_label4;
lv_obj_t * ui_jog_roller_jogdist;
lv_obj_t * ui_jog_container_container4;
lv_obj_t * ui_jog_label_label5;
lv_obj_t * ui_jog_roller_jogfeed;
lv_obj_t * ui_jog_container_container5;
lv_obj_t * ui_jog_label_label6;
lv_obj_t * ui_jog_roller_jogaxis;
lv_obj_t * ui_jog_container_container6;
void ui_event_jog_button_btnjogplus(lv_event_t * e);
lv_obj_t * ui_jog_button_btnjogplus;
lv_obj_t * ui_jog_image_image3;
void ui_event_jog_button_btnjogcancel(lv_event_t * e);
lv_obj_t * ui_jog_button_btnjogcancel;
lv_obj_t * ui_jog_image_image4;
void ui_event_jog_button_btnjogminus(lv_event_t * e);
lv_obj_t * ui_jog_button_btnjogminus;
lv_obj_t * ui_jog_image_image5;


// SCREEN: ui_alarm
void ui_alarm_screen_init(void);
lv_obj_t * ui_alarm;
lv_obj_t * ui_alarm_image_imgalarm;
lv_obj_t * ui_alarm_label_alarmcode;
lv_obj_t * ui_alarm_label_alarmmessage;
void ui_event_alarm_button_btnreset(lv_event_t * e);
lv_obj_t * ui_alarm_button_btnreset;
lv_obj_t * ui_alarm_label_label3;
lv_obj_t * ui_alarm_image_image19;
lv_obj_t * ui_startevents____initial_actions0;
const lv_image_dsc_t * ui_imgset_home[1] = {&ui_img_home3_png};
const lv_image_dsc_t * ui_imgset_loop[1] = {&ui_img_loop2_png};
const lv_image_dsc_t * ui_imgset_pause[1] = {&ui_img_pause2_png};
const lv_image_dsc_t * ui_imgset_play[1] = {&ui_img_play3_png};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_idle_button_btnunlock(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        touch_btn_unlock_cb(e);
    }
}
void ui_event_idle_button_btnholdres(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        touch_btn_hold_cb(e);
    }
}
void ui_event_idle_button_btnhome(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        touch_btn_home_cb(e);
    }
}
void ui_event_idle_button_btnjog(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        touch_btn_jog_cb(e);
    }
}
void ui_event_idle_button_btnsettings(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        touch_btn_settings_cb(e);
    }
}
void ui_event_idle_button_btnprev2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        touch_btn_prev_cb(e);
    }
}
void ui_event_idle_button_btnnext2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        touch_btn_next_cb(e);
    }
}
void ui_event_idle_button_btnenter2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        touch_btn_enter_cb(e);
    }
}
void ui_event_navigate_button_btnclose(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        touch_btn_close_cb(e);
    }
}
void ui_event_navigate_button_btnprev(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        touch_btn_prev_cb(e);
    }
}
void ui_event_navigate_button_btnnext(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        touch_btn_next_cb(e);
    }
}
void ui_event_navigate_button_btnenter(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        touch_btn_enter_cb(e);
    }
}
void ui_event_edit_button_btnclose(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        touch_btn_close_cb(e);
    }
}
void ui_event_edit_keyboard_keyboardedit(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_READY) {
        touch_kb_ready_ev(e);
    }
}
void ui_event_jog_button_btnclose(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        touch_btn_close_cb(e);
    }
}
void ui_event_jog_button_btnjogplus(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_PRESSED) {
        touch_btn_jogplus_cb(e);
    }
    if(event_code == LV_EVENT_LONG_PRESSED_REPEAT) {
        touch_btn_jogplus_cb(e);
    }
    if(event_code == LV_EVENT_RELEASED) {
        touch_btn_jogcancel_repeat_cb(e);
    }
}
void ui_event_jog_button_btnjogcancel(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        touch_btn_jogcancel_cb(e);
    }
}
void ui_event_jog_button_btnjogminus(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        touch_btn_jogminus_cb(e);
    }
    if(event_code == LV_EVENT_LONG_PRESSED_REPEAT) {
        touch_btn_jogminus_cb(e);
    }
    if(event_code == LV_EVENT_RELEASED) {
        touch_btn_jogcancel_repeat_cb(e);
    }
}
void ui_event_alarm_button_btnreset(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        touch_btn_reset_cb(e);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    LV_EVENT_GET_COMP_CHILD = lv_event_register_id();

    lv_disp_t * dispp = lv_display_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_startup_screen_init();
    ui_idle_screen_init();
    ui_navigate_screen_init();
    ui_edit_screen_init();
    ui_jog_screen_init();
    ui_alarm_screen_init();
    ui_startevents____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_startup);
}
