// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: uCNC-GFX

#ifndef _UCNC_GFX_UI_H
#define _UCNC_GFX_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "src/modules/mks_display/lvgl/lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_comp.h"
#include "ui_comp_hook.h"
#include "ui_events.h"
#include "ui_theme_manager.h"
#include "ui_themes.h"

// SCREEN: ui_startup
void ui_startup_screen_init(void);
extern lv_obj_t * ui_startup;
extern lv_obj_t * ui_startup_label_versioninfo;
extern lv_obj_t * ui_startup_image_image1;
// SCREEN: ui_idle
void ui_idle_screen_init(void);
extern lv_obj_t * ui_idle;
extern lv_obj_t * ui_idle_container_header2;
void ui_event_idle_button_btnunlock(lv_event_t * e);
extern lv_obj_t * ui_idle_button_btnunlock;
extern lv_obj_t * ui_idle_image_image8;
extern lv_obj_t * ui_idle_image_image17;
extern lv_obj_t * ui_idle_container_statusinfo;
extern lv_obj_t * ui_idle_label_statuslabel;
extern lv_obj_t * ui_idle_label_statusvalue;
void ui_event_idle_button_btnholdres(lv_event_t * e);
extern lv_obj_t * ui_idle_button_btnholdres;
extern lv_obj_t * ui_idle_image_image7;
extern lv_obj_t * ui_idle_image_image12;
extern lv_obj_t * ui_idle_container_body2;
extern lv_obj_t * ui_idle_container_container7;
void ui_event_idle_button_btnhome(lv_event_t * e);
extern lv_obj_t * ui_idle_button_btnhome;
extern lv_obj_t * ui_idle_image_image9;
void ui_event_idle_button_btnjog(lv_event_t * e);
extern lv_obj_t * ui_idle_button_btnjog;
extern lv_obj_t * ui_idle_image_image10;
void ui_event_idle_button_btnsettings(lv_event_t * e);
extern lv_obj_t * ui_idle_button_btnsettings;
extern lv_obj_t * ui_idle_image_image11;
extern lv_obj_t * ui_idle_container_container1;
extern lv_obj_t * ui_idle_container_modalmodesinfo;
extern lv_obj_t * ui_idle_label_modalmodeslabel;
extern lv_obj_t * ui_idle_label_modalmodesvalue;
extern lv_obj_t * ui_idle_container_container3;
extern lv_obj_t * ui_idle_label_unitsvalue;
extern lv_obj_t * ui_idle_container_feedinfo;
extern lv_obj_t * ui_idle_label_feedlabel;
extern lv_obj_t * ui_idle_label_feedvalue;
extern lv_obj_t * ui_idle_container_toolnumberinfo;
extern lv_obj_t * ui_idle_label_toolnumberlabel;
extern lv_obj_t * ui_idle_label_toolnumbervalue;
extern lv_obj_t * ui_idle_container_toolspeedinfo;
extern lv_obj_t * ui_idle_label_toolspeedlabel;
extern lv_obj_t * ui_idle_label_toolspeedvalue;
extern lv_obj_t * ui_idle_container_switchinfo;
extern lv_obj_t * ui_idle_label_switchlabel;
extern lv_obj_t * ui_idle_label_switchvalue;
extern lv_obj_t * ui_idle_container_container8;
extern lv_obj_t * ui_idle_axisinfo_axisinfox;
extern lv_obj_t * ui_idle_axisinfo_axisinfoy;
extern lv_obj_t * ui_idle_axisinfo_axisinfoz;
extern lv_obj_t * ui_idle_container_container9;
extern lv_obj_t * ui_idle_axisinfo_axisinfoa;
extern lv_obj_t * ui_idle_axisinfo_axisinfob;
extern lv_obj_t * ui_idle_axisinfo_axisinfoc;
extern lv_obj_t * ui_idle_container_footer2;
void ui_event_idle_button_btnprev2(lv_event_t * e);
extern lv_obj_t * ui_idle_button_btnprev2;
extern lv_obj_t * ui_idle_label_btnprevlabel2;
void ui_event_idle_button_btnnext2(lv_event_t * e);
extern lv_obj_t * ui_idle_button_btnnext2;
extern lv_obj_t * ui_idle_label_btnnextlabel2;
void ui_event_idle_button_btnenter2(lv_event_t * e);
extern lv_obj_t * ui_idle_button_btnenter2;
extern lv_obj_t * ui_idle_label_btnenterlabel2;
// SCREEN: ui_navigate
void ui_navigate_screen_init(void);
extern lv_obj_t * ui_navigate;
extern lv_obj_t * ui_navigate_panel_header;
extern lv_obj_t * ui_navigate_label_headerlabel;
void ui_event_navigate_button_btnclose(lv_event_t * e);
extern lv_obj_t * ui_navigate_button_btnclose;
extern lv_obj_t * ui_navigate_image_image16;
extern lv_obj_t * ui_navigate_container_body;
extern lv_obj_t * ui_navigate_container_menuitem0;
extern lv_obj_t * ui_navigate_label_menuitemlabel0;
extern lv_obj_t * ui_navigate_label_menuitemvalue0;
extern lv_obj_t * ui_navigate_container_menuitem1;
extern lv_obj_t * ui_navigate_label_menuitemlabel1;
extern lv_obj_t * ui_navigate_label_menuitemvalue1;
extern lv_obj_t * ui_navigate_container_menuitem2;
extern lv_obj_t * ui_navigate_label_menuitemlabel2;
extern lv_obj_t * ui_navigate_label_menuitemvalue2;
extern lv_obj_t * ui_navigate_container_menuitem3;
extern lv_obj_t * ui_navigate_label_menuitemlabel3;
extern lv_obj_t * ui_navigate_label_menuitemvalue3;
extern lv_obj_t * ui_navigate_container_menuitem4;
extern lv_obj_t * ui_navigate_label_menuitemlabel4;
extern lv_obj_t * ui_navigate_label_menuitemvalue4;
extern lv_obj_t * ui_navigate_container_menuitem5;
extern lv_obj_t * ui_navigate_label_menuitemlabel5;
extern lv_obj_t * ui_navigate_label_menuitemvalue5;
extern lv_obj_t * ui_navigate_panel_footernav;
void ui_event_navigate_button_btnprev(lv_event_t * e);
extern lv_obj_t * ui_navigate_button_btnprev;
extern lv_obj_t * ui_navigate_image_image13;
void ui_event_navigate_button_btnnext(lv_event_t * e);
extern lv_obj_t * ui_navigate_button_btnnext;
extern lv_obj_t * ui_navigate_image_image14;
void ui_event_navigate_button_btnenter(lv_event_t * e);
extern lv_obj_t * ui_navigate_button_btnenter;
extern lv_obj_t * ui_navigate_image_image15;
// SCREEN: ui_edit
void ui_edit_screen_init(void);
extern lv_obj_t * ui_edit;
extern lv_obj_t * ui_edit_panel_header;
extern lv_obj_t * ui_edit_label_headerlabel;
void ui_event_edit_button_btnclose(lv_event_t * e);
extern lv_obj_t * ui_edit_button_btnclose;
extern lv_obj_t * ui_edit_image_image2;
extern lv_obj_t * ui_edit_container_bodyedit;
extern lv_obj_t * ui_edit_textarea_vareditinput;
extern lv_obj_t * ui_edit_container_footeredit;
void ui_event_edit_keyboard_keyboardedit(lv_event_t * e);
extern lv_obj_t * ui_edit_keyboard_keyboardedit;
// SCREEN: ui_jog
void ui_jog_screen_init(void);
extern lv_obj_t * ui_jog;
extern lv_obj_t * ui_jog_panel_header;
extern lv_obj_t * ui_jog_label_headerlabel;
void ui_event_jog_button_btnclose(lv_event_t * e);
extern lv_obj_t * ui_jog_button_btnclose;
extern lv_obj_t * ui_jog_image_image6;
extern lv_obj_t * ui_jog_container_body1;
extern lv_obj_t * ui_jog_container_jogaxisinfo;
extern lv_obj_t * ui_jog_label_jogaxislabel;
extern lv_obj_t * ui_jog_label_jogaxisvalue;
extern lv_obj_t * ui_jog_panel_panel1;
extern lv_obj_t * ui_jog_container_container2;
extern lv_obj_t * ui_jog_label_label4;
extern lv_obj_t * ui_jog_roller_jogdist;
extern lv_obj_t * ui_jog_container_container4;
extern lv_obj_t * ui_jog_label_label5;
extern lv_obj_t * ui_jog_roller_jogfeed;
extern lv_obj_t * ui_jog_container_container5;
extern lv_obj_t * ui_jog_label_label6;
extern lv_obj_t * ui_jog_roller_jogaxis;
extern lv_obj_t * ui_jog_container_container6;
void ui_event_jog_button_btnjogplus(lv_event_t * e);
extern lv_obj_t * ui_jog_button_btnjogplus;
extern lv_obj_t * ui_jog_image_image3;
void ui_event_jog_button_btnjogcancel(lv_event_t * e);
extern lv_obj_t * ui_jog_button_btnjogcancel;
extern lv_obj_t * ui_jog_image_image4;
void ui_event_jog_button_btnjogminus(lv_event_t * e);
extern lv_obj_t * ui_jog_button_btnjogminus;
extern lv_obj_t * ui_jog_image_image5;
// SCREEN: ui_alarm
void ui_alarm_screen_init(void);
extern lv_obj_t * ui_alarm;
extern lv_obj_t * ui_alarm_image_imgalarm;
extern lv_obj_t * ui_alarm_label_alarmcode;
extern lv_obj_t * ui_alarm_label_alarmmessage;
void ui_event_alarm_button_btnreset(lv_event_t * e);
extern lv_obj_t * ui_alarm_button_btnreset;
extern lv_obj_t * ui_alarm_label_label3;
extern lv_obj_t * ui_alarm_image_image19;
extern lv_obj_t * ui_startevents____initial_actions0;


LV_IMG_DECLARE(ui_img_ucnc_lowres_png);    // assets/uCNC_lowres.png
LV_IMG_DECLARE(ui_img_lock_png);    // assets/lock.png
LV_IMG_DECLARE(ui_img_unlocked_png);    // assets/unlocked.png
LV_IMG_DECLARE(ui_img_pause2_png);    // assets/pause2.png
LV_IMG_DECLARE(ui_img_play3_png);    // assets/play3.png
LV_IMG_DECLARE(ui_img_home3_png);    // assets/home3.png
LV_IMG_DECLARE(ui_img_enlarge_png);    // assets/enlarge.png
LV_IMG_DECLARE(ui_img_cog_png);    // assets/cog.png
LV_IMG_DECLARE(ui_img_cross_png);    // assets/cross.png
LV_IMG_DECLARE(ui_img_221678416);    // assets/arrow-up.png
LV_IMG_DECLARE(ui_img_1491226653);    // assets/arrow-down.png
LV_IMG_DECLARE(ui_img_checkmark_png);    // assets/checkmark.png
LV_IMG_DECLARE(ui_img_blocked_png);    // assets/blocked.png
LV_IMG_DECLARE(ui_img_warning_png);    // assets/warning.png
LV_IMG_DECLARE(ui_img_loop2_png);    // assets/loop2.png






void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
