// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: uCNC-GFX

#include "ui.h"

void ui_alarm_screen_init(void)
{
    ui_alarm = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_alarm, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_flex_flow(ui_alarm, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_alarm, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    ui_object_set_themeable_style_property(ui_alarm, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_alarm);
    ui_object_set_themeable_style_property(ui_alarm, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_alarm);

    ui_alarm_image_imgalarm = lv_image_create(ui_alarm);
    lv_image_set_src(ui_alarm_image_imgalarm, &ui_img_warning_png);
    lv_obj_set_width(ui_alarm_image_imgalarm, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_alarm_image_imgalarm, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_alarm_image_imgalarm, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_alarm_image_imgalarm, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_alarm_image_imgalarm, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_alarm_label_alarmcode = lv_label_create(ui_alarm);
    lv_obj_set_width(ui_alarm_label_alarmcode, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_alarm_label_alarmcode, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_alarm_label_alarmcode, LV_ALIGN_CENTER);
    lv_label_set_text(ui_alarm_label_alarmcode, "ALARM");

    ui_alarm_label_alarmmessage = lv_label_create(ui_alarm);
    lv_obj_set_width(ui_alarm_label_alarmmessage, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_alarm_label_alarmmessage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_alarm_label_alarmmessage, LV_ALIGN_CENTER);
    lv_label_set_text(ui_alarm_label_alarmmessage, "text");

    ui_alarm_button_btnreset = lv_button_create(ui_alarm);
    lv_obj_set_height(ui_alarm_button_btnreset, 50);
    lv_obj_set_width(ui_alarm_button_btnreset, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_align(ui_alarm_button_btnreset, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_alarm_button_btnreset, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_alarm_button_btnreset, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(ui_alarm_button_btnreset, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_alarm_button_btnreset, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_alarm_button_btnreset, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_alarm);
    ui_object_set_themeable_style_property(ui_alarm_button_btnreset, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_alarm);
    lv_obj_set_style_border_color(ui_alarm_button_btnreset, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_alarm_button_btnreset, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_alarm_button_btnreset, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_alarm_button_btnreset, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_alarm_button_btnreset, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_alarm_button_btnreset, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_alarm_button_btnreset, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_alarm_button_btnreset, LV_PART_MAIN | LV_STATE_PRESSED, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_alarmpressed);
    ui_object_set_themeable_style_property(ui_alarm_button_btnreset, LV_PART_MAIN | LV_STATE_PRESSED, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_alarmpressed);

    ui_alarm_label_label3 = lv_label_create(ui_alarm_button_btnreset);
    lv_obj_set_width(ui_alarm_label_label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_alarm_label_label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_alarm_label_label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_alarm_label_label3, "Reset");

    ui_alarm_image_image19 = lv_image_create(ui_alarm_button_btnreset);
    lv_image_set_src(ui_alarm_image_image19, &ui_img_loop2_png);
    lv_obj_set_width(ui_alarm_image_image19, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_alarm_image_image19, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_alarm_image_image19, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_alarm_image_image19, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_alarm_image_image19, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_alarm_button_btnreset, ui_event_alarm_button_btnreset, LV_EVENT_ALL, NULL);

}
