// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: uCNC-GFX

#ifndef _UI_COMP_AXISINFO_H
#define _UI_COMP_AXISINFO_H

#include "ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT AxisInfo
#define UI_COMP_CONTAINER_AXISINFO_CONTAINER_AXISINFO 0
#define UI_COMP_CONTAINER_AXISINFO_LABEL_AXISLABEL 1
#define UI_COMP_CONTAINER_AXISINFO_LABEL_AXISVALUE 2
#define _UI_COMP_CONTAINER_AXISINFO_NUM 3
lv_obj_t * ui_container_axisinfo_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
