// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: uCNC-GFX

#ifndef _UCNC_GFX_UI_COMP_HOOK_H
#define _UCNC_GFX_UI_COMP_HOOK_H

#ifdef __cplusplus
extern "C" {
#endif

void ui_comp_container_axisinfo_create_hook(lv_obj_t * comp);
void ui_comp_container_headertemplate_create_hook(lv_obj_t * comp);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
