// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: uCNC-GFX

#include "ui.h"


void ui_event_comp_container_headertemplate_button_btnhome(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    lv_obj_t ** comp_container_headertemplate = lv_event_get_user_data(e);
    if(event_code == LV_EVENT_CLICKED) {
        touch_btn_home_cb(e);
    }
}
void ui_event_comp_container_headertemplate_button_btnholdres(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    lv_obj_t ** comp_container_headertemplate = lv_event_get_user_data(e);
    if(event_code == LV_EVENT_CLICKED) {
        touch_btn_hold_cb(e);
    }
}

// COMPONENT HeaderTemplate

lv_obj_t * ui_container_headertemplate_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_container_headertemplate;
    cui_container_headertemplate = lv_obj_create(comp_parent);
    lv_obj_remove_style_all(cui_container_headertemplate);
    lv_obj_set_width(cui_container_headertemplate, lv_pct(100));
    lv_obj_set_height(cui_container_headertemplate, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(cui_container_headertemplate, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(cui_container_headertemplate, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(cui_container_headertemplate, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER,
                          LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(cui_container_headertemplate, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_row(cui_container_headertemplate, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(cui_container_headertemplate, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_button_btnhome;
    cui_button_btnhome = lv_button_create(cui_container_headertemplate);
    lv_obj_set_height(cui_button_btnhome, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_flex_grow(cui_button_btnhome, 1);
    lv_obj_set_align(cui_button_btnhome, LV_ALIGN_CENTER);
    lv_obj_add_flag(cui_button_btnhome, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(cui_button_btnhome, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t * cui_label_btnhomelabel;
    cui_label_btnhomelabel = lv_label_create(cui_button_btnhome);
    lv_obj_set_width(cui_label_btnhomelabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_label_btnhomelabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(cui_label_btnhomelabel, LV_ALIGN_CENTER);
    lv_label_set_text(cui_label_btnhomelabel, "Home");

    lv_obj_t * cui_container_statusinfo;
    cui_container_statusinfo = lv_obj_create(cui_container_headertemplate);
    lv_obj_remove_style_all(cui_container_statusinfo);
    lv_obj_set_height(cui_container_statusinfo, LV_SIZE_CONTENT);    /// 100
    lv_obj_set_flex_grow(cui_container_statusinfo, 2);
    lv_obj_set_align(cui_container_statusinfo, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(cui_container_statusinfo, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(cui_container_statusinfo, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(cui_container_statusinfo, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(cui_container_statusinfo, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(cui_container_statusinfo, lv_color_hex(0xAF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_container_statusinfo, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(cui_container_statusinfo, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(cui_container_statusinfo, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(cui_container_statusinfo, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(cui_container_statusinfo, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(cui_container_statusinfo, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(cui_container_statusinfo, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_label_statuslabel;
    cui_label_statuslabel = lv_label_create(cui_container_statusinfo);
    lv_obj_set_width(cui_label_statuslabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_label_statuslabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(cui_label_statuslabel, LV_ALIGN_CENTER);
    lv_label_set_text(cui_label_statuslabel, "St:");

    lv_obj_t * cui_label_statusvalue;
    cui_label_statusvalue = lv_label_create(cui_container_statusinfo);
    lv_obj_set_width(cui_label_statusvalue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_label_statusvalue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(cui_label_statusvalue, LV_ALIGN_CENTER);
    lv_label_set_text(cui_label_statusvalue, "Alarm");

    lv_obj_t * cui_button_btnholdres;
    cui_button_btnholdres = lv_button_create(cui_container_headertemplate);
    lv_obj_set_height(cui_button_btnholdres, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_flex_grow(cui_button_btnholdres, 1);
    lv_obj_set_align(cui_button_btnholdres, LV_ALIGN_CENTER);
    lv_obj_add_flag(cui_button_btnholdres, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(cui_button_btnholdres, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(cui_button_btnholdres, lv_color_hex(0xD6BD38), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_button_btnholdres, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_label_btnholdreslabel;
    cui_label_btnholdreslabel = lv_label_create(cui_button_btnholdres);
    lv_obj_set_width(cui_label_btnholdreslabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_label_btnholdreslabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(cui_label_btnholdreslabel, LV_ALIGN_CENTER);
    lv_label_set_text(cui_label_btnholdreslabel, "Hold");

    lv_obj_t ** children = lv_malloc(sizeof(lv_obj_t *) * _UI_COMP_CONTAINER_HEADERTEMPLATE_NUM);
    children[UI_COMP_CONTAINER_HEADERTEMPLATE_CONTAINER_HEADERTEMPLATE] = cui_container_headertemplate;
    children[UI_COMP_CONTAINER_HEADERTEMPLATE_BUTTON_BTNHOME] = cui_button_btnhome;
    children[UI_COMP_CONTAINER_HEADERTEMPLATE_BUTTON_BTNHOME_LABEL_BTNHOMELABEL] = cui_label_btnhomelabel;
    children[UI_COMP_CONTAINER_HEADERTEMPLATE_CONTAINER_STATUSINFO] = cui_container_statusinfo;
    children[UI_COMP_CONTAINER_HEADERTEMPLATE_CONTAINER_STATUSINFO_LABEL_STATUSLABEL] = cui_label_statuslabel;
    children[UI_COMP_CONTAINER_HEADERTEMPLATE_CONTAINER_STATUSINFO_LABEL_STATUSVALUE] = cui_label_statusvalue;
    children[UI_COMP_CONTAINER_HEADERTEMPLATE_BUTTON_BTNHOLDRES] = cui_button_btnholdres;
    children[UI_COMP_CONTAINER_HEADERTEMPLATE_BUTTON_BTNHOLDRES_LABEL_BTNHOLDRESLABEL] = cui_label_btnholdreslabel;
    lv_obj_add_event_cb(cui_container_headertemplate, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_container_headertemplate, del_component_child_event_cb, LV_EVENT_DELETE, children);
    lv_obj_add_event_cb(cui_button_btnhome, ui_event_comp_container_headertemplate_button_btnhome, LV_EVENT_ALL, children);
    lv_obj_add_event_cb(cui_button_btnholdres, ui_event_comp_container_headertemplate_button_btnholdres, LV_EVENT_ALL,
                        children);
    ui_comp_container_headertemplate_create_hook(cui_container_headertemplate);
    return cui_container_headertemplate;
}

