// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: uCNC-GFX

#include "ui.h"

void ui_startup_screen_init(void)
{
    ui_startup = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_startup, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_startup, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_startup, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_startup, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_startup, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_startup, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_startup, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_startup, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_startup_label_versioninfo = lv_label_create(ui_startup);
    lv_obj_set_width(ui_startup_label_versioninfo, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_startup_label_versioninfo, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_startup_label_versioninfo, -5);
    lv_obj_set_y(ui_startup_label_versioninfo, -5);
    lv_obj_set_align(ui_startup_label_versioninfo, LV_ALIGN_BOTTOM_RIGHT);
    lv_label_set_text(ui_startup_label_versioninfo, "uCNC vX.X.X");
    lv_obj_set_style_text_color(ui_startup_label_versioninfo, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_startup_label_versioninfo, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_startup_image_image1 = lv_image_create(ui_startup);
    lv_image_set_src(ui_startup_image_image1, &ui_img_ucnc_lowres_png);
    lv_obj_set_width(ui_startup_image_image1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_startup_image_image1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_startup_image_image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_startup_image_image1, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_startup_image_image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

}
