// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: uCNC-GFX

#include "ui.h"


const ui_theme_variable_t _ui_theme_color_button[1] = {0x507C51};
const ui_theme_variable_t _ui_theme_alpha_button[1] = {255};

const ui_theme_variable_t _ui_theme_color_buttonpressed[1] = {0x2C442D};
const ui_theme_variable_t _ui_theme_alpha_buttonpressed[1] = {255};

const ui_theme_variable_t _ui_theme_color_alarm[1] = {0xC82121};
const ui_theme_variable_t _ui_theme_alpha_alarm[1] = {255};

const ui_theme_variable_t _ui_theme_color_hold[1] = {0xD7A50E};
const ui_theme_variable_t _ui_theme_alpha_hold[1] = {255};

const ui_theme_variable_t _ui_theme_color_alarmpressed[1] = {0x991A1A};
const ui_theme_variable_t _ui_theme_alpha_alarmpressed[1] = {255};

const ui_theme_variable_t _ui_theme_color_checked[1] = {0x006595};
const ui_theme_variable_t _ui_theme_alpha_checked[1] = {255};

const ui_theme_variable_t _ui_theme_color_container[1] = {0x303030};
const ui_theme_variable_t _ui_theme_alpha_container[1] = {255};
uint8_t ui_theme_idx = UI_THEME_DEFAULT;


void ui_theme_set(uint8_t theme_idx)
{
    ui_theme_idx = theme_idx;
    _ui_theme_set_variable_styles(UI_VARIABLE_STYLES_MODE_FOLLOW);
}

